//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PODER_JUDICIALEntities : DbContext
    {
        public PODER_JUDICIALEntities()
            : base("name=PODER_JUDICIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DEMANDA> TB_DEMANDA { get; set; }
        public virtual DbSet<TB_DEMANDADO> TB_DEMANDADO { get; set; }
        public virtual DbSet<TB_DEMANDADO_EMPRESA> TB_DEMANDADO_EMPRESA { get; set; }
        public virtual DbSet<TB_DEMANDADO_PERSONA> TB_DEMANDADO_PERSONA { get; set; }
        public virtual DbSet<TB_DEMANDANTE> TB_DEMANDANTE { get; set; }
        public virtual DbSet<TB_DETALLE_DEMANDA> TB_DETALLE_DEMANDA { get; set; }
        public virtual DbSet<TB_REPRESENTANTE> TB_REPRESENTANTE { get; set; }
    }
}
