//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEMANDADO_PERSONA
    {
        public string COD_DADO { get; set; }
        public string NOM_DADO { get; set; }
        public string APEPAT_DADO { get; set; }
        public string APEMAT_DADO { get; set; }
    
        public virtual TB_DEMANDADO TB_DEMANDADO { get; set; }
    }
}
