//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DETALLE_DEMANDA
    {
        public string NUM_DEMANDA { get; set; }
        public int NUM_PET { get; set; }
        public decimal MON_PET { get; set; }
        public string DESCRIP_PET { get; set; }
        public string PRUEBA_PET { get; set; }
        public string JUSTIF_PET { get; set; }
    
        public virtual TB_DEMANDA TB_DEMANDA { get; set; }
    }
}
