//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class TB_DEMANDADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DEMANDADO()
        {
            this.TB_DEMANDA = new HashSet<TB_DEMANDA>();
        }
    
        public string COD_DADO { get; set; }
        public string DOM_DADO { get; set; }
        public string COD_REPRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DEMANDA> TB_DEMANDA { get; set; }
        public virtual TB_DEMANDADO_PERSONA TB_DEMANDADO_PERSONA { get; set; }
        public virtual TB_DEMANDADO_EMPRESA TB_DEMANDADO_EMPRESA { get; set; }
        public virtual TB_REPRESENTANTE TB_REPRESENTANTE { get; set; }

        public List<TB_DEMANDADO> Listar(int pageIndex, int pageSize, out int pageCount)
        {
            List<TB_DEMANDADO> orders = new List<TB_DEMANDADO>();
            using (SqlConnection conexion = new SqlConnection("Data Source=ARANTXA-PC\\SQLEXPRESS;Initial Catalog=PODER_JUDICIAL;Integrated Security=True;"))
            {
                conexion.Open();
                using (SqlCommand comando = new SqlCommand("Usp_demandado_Listar", conexion))
                {
                    comando.CommandType = CommandType.StoredProcedure;
                    comando.CommandTimeout = 0;
                    comando.Parameters.AddWithValue("@pageIndex", pageIndex);
                    comando.Parameters.AddWithValue("@pageSize", pageSize);
                    comando.Parameters.AddWithValue("@pageCount", 0).Direction = ParameterDirection.Output;
                    using (SqlDataReader reader = comando.ExecuteReader())
                    {
                        if (reader != null)
                        {
                            TB_DEMANDADO order = null;
                            while (reader.Read())
                            {
                                order = new TB_DEMANDADO();
                                order.COD_DADO = (String)reader["COD_DADO"];
                                order.COD_REPRE = (String)reader["COD_REPRE"];
                                order.DOM_DADO = (String)reader["DOM_DADO"];
                                orders.Add(order);
                            }
                        }
                    }

                    pageCount = (int)comando.Parameters["@pageCount"].Value;
                }
            }
            return orders;
        }
        public String generarCodigo()
        {
            String codigo = "";
            using (SqlConnection conexion = new SqlConnection("Data Source=ARANTXA-PC\\SQLEXPRESS;Initial Catalog=PODER_JUDICIAL;Integrated Security=True;"))
            {
                conexion.Open();
                using (SqlCommand comando = new SqlCommand("cagDemandado", conexion))
                {
                    comando.CommandType = CommandType.StoredProcedure;

                    codigo = comando.ExecuteScalar().ToString();
                }


                return codigo;
            }

        }

        public String generarCodigoDetalle()
        {
            String codigo = "";
            using (SqlConnection conexion = new SqlConnection("Data Source=ARANTXA-PC\\SQLEXPRESS;Initial Catalog=PODER_JUDICIAL;Integrated Security=True;"))
            {
                conexion.Open();
                using (SqlCommand comando = new SqlCommand("cagDemandadoDetalle", conexion))
                {
                    comando.CommandType = CommandType.StoredProcedure;

                    codigo = comando.ExecuteScalar().ToString();
                }


                return codigo;
            }

        }


    }

}
