//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class TB_REPRESENTANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_REPRESENTANTE()
        {
            this.TB_DEMANDADO = new HashSet<TB_DEMANDADO>();
            this.TB_DEMANDANTE = new HashSet<TB_DEMANDANTE>();
        }
    
        public string COD_REPRE { get; set; }
        public string NOM_REPRE { get; set; }
        public string APEPAT_REPRE { get; set; }
        public string APEMAT_REPRE { get; set; }
        public string DNI_REPRE { get; set; }
        public string DOMREAL_REPRE { get; set; }
        public string DOMLEG_REPRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DEMANDADO> TB_DEMANDADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DEMANDANTE> TB_DEMANDANTE { get; set; }

        public List<TB_REPRESENTANTE> Listar(int pageIndex, int pageSize, out int pageCount)
        {
            List<TB_REPRESENTANTE> orders = new List<TB_REPRESENTANTE>();
            using (SqlConnection conexion = new SqlConnection("Data Source=ARANTXA-PC\\SQLEXPRESS;Initial Catalog=PODER_JUDICIAL;Integrated Security=True;"))
            {
                conexion.Open();
                using (SqlCommand comando = new SqlCommand("Usp_representante_Listar", conexion))
                {
                    comando.CommandType = CommandType.StoredProcedure;
                    comando.CommandTimeout = 0;
                    comando.Parameters.AddWithValue("@pageIndex", pageIndex);
                    comando.Parameters.AddWithValue("@pageSize", pageSize);
                    comando.Parameters.AddWithValue("@pageCount", 0).Direction = ParameterDirection.Output;
                    using (SqlDataReader reader = comando.ExecuteReader())
                    {
                        if (reader != null)
                        {
                            TB_REPRESENTANTE order = null;
                            while (reader.Read())
                            {
                                order = new TB_REPRESENTANTE();
                                order.COD_REPRE = (String)reader["COD_REPRE"];
                                order.NOM_REPRE = (String)reader["NOM_REPRE"];
                                order.APEPAT_REPRE = (String)reader["APEPAT_REPRE"];
                                order.APEMAT_REPRE = (String)reader["APEMAT_REPRE"];
                                order.DNI_REPRE = (String)reader["DNI_REPRE"];
                                order.DOMREAL_REPRE = (String)reader["DOMREAL_REPRE"];
                                order.DOMLEG_REPRE = (String)reader["DOMLEG_REPRE"];
                                orders.Add(order);
                            }
                        }
                    }

                    pageCount = (int)comando.Parameters["@pageCount"].Value;
                }
            }
            return orders;
        }

        public String generarCodigo()
        {
            String codigo = "";
            using (SqlConnection conexion = new SqlConnection("Data Source=ARANTXA-PC\\SQLEXPRESS;Initial Catalog=PODER_JUDICIAL;Integrated Security=True;"))
            {
                conexion.Open();
                using (SqlCommand comando = new SqlCommand("cagRepresentante", conexion))
                {
                    comando.CommandType = CommandType.StoredProcedure;

                    codigo = comando.ExecuteScalar().ToString();
                }


                return codigo;
            }

        }
    }
}
